### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA#1]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by osdamart** [comment]
Ok, we'll work on it

**Comment by jose598** [comment]
Thank you

**Comment by osdamart** [comment]
We have categorized the issue already

**Comment by osdamart** [comment]
We'll proceed to process the request, @Ronny-Andrade will be the assigned analyst and will develop the solution, then @RicardoVilcacundo will perform the tests.

**Comment by jose598** [comment]
Thank you! @osdamart

**Comment by Ronny-Andrade** [comment]
[Impact analysis.docx](https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/files/7917146/Impact.analysis.docx)

This is our impact analysis, @jose598 is it okay?

**Comment by jose598** [comment]
@Ronny-Andrade I need to take a look about hoy you are calculating theses rules/cases. Please send a table with all cases applied.

**Comment by osdamart** [comment]
The table is with all the cases or only these two from the new bussiness goal? @jose598

**Comment by jose598** [comment]
Just with two cases.

**Comment by Ronny-Andrade** [comment]
[All new cases.docx](https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/files/7917207/All.new.cases.docx)

this is the table @jose598

**Comment by jose598** [comment]
OK, thank you. start working with the issue.

**Comment by Ronny-Andrade** [comment]
the solution has been built 

https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/blob/1cbe6b2ce15ccfcdcfa8bf1024bf5b19176aa704/ec.edu.espol.workshops/src/ec/edu/espol/workshops/CarInsurance.java#L94-L99
@jose598

**Comment by jose598** [comment]
I have observation, the discount according to the first case/rule is about $100, because the discount is $50 for each one.

Please change this and on your analysis report.
@Ronny-Andrade

**Comment by osdamart** [comment]
Okk , we'll make these changes ASAP, sorry for the misunderstanding

**Comment by Ronny-Andrade** [comment]
this is the new  impact analysis  corrected
[updated.docx](https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/files/7917319/updated.docx)

Code correction

https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/blob/10e46bdef18dc05d89a4f529eaba226d75e7203d/ec.edu.espol.workshops/src/ec/edu/espol/workshops/CarInsurance.java#L94-L99

@jose598

**Comment by jose598** [comment]
Thank you @Ronny-Andrade. 
Start working with the issue

**Comment by osdamart** [comment]
@jose598  The solution has been completed and the programmer, @Ronny-Andrade will release the new software version for you

**Comment by jose598** [comment]
What about the test plan? @osdamart

**Comment by osdamart** [comment]
Due to technical issues and lack of time we wanted to know if we could continue without the unit tests, we already have the user mannual to give you the guide of how to use the software propertly

**Comment by osdamart** [comment]
Sorry, @RicardoVilcacundo will attach the test plan in a few

**Comment by jose598** [comment]
@osdamart Got it.

**Comment by RicardoVilcacundo** [comment]
Sorry for the delay, here is the test plan with the results of it
[Test Plan PU.docx](https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/files/7917504/Test.Plan.PU.docx)

**Comment by RicardoVilcacundo** [comment]
@jose598

**Comment by jose598** [comment]
Thank you! @RicardoVilcacundo continue with the release

**Comment by osdamart** [comment]
@jose598  thank you, @Ronny-Andrade will release the new software version for you

**Comment by Ronny-Andrade** [comment]
this is the manual guide 
[Software Instruction.docx](https://github.com/osdamart/ISII-WORKSHOPS-PARRILLADA_URUGUAYA/files/7917564/Software.Instruction.docx)
 @jose598

**Comment by Ronny-Andrade** [comment]
if you have been able to use the software?
are you satisfied with the solution?
@jose598

**Comment by jose598** [comment]
Ok, it's sound good.
I satisfy with this, so you can close this issue.

**Comment by osdamart** [comment]
We apreciate it :-D , I'll proceed to close this issue then
